name: go_sport
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.9.2

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8

    freezed_annotation: ^2.4.4
    json_annotation: ^4.9.0

    flutter_riverpod: ^2.5.1
    google_sign_in: ^7.2.0
    cached_network_image: ^3.4.1
    google_fonts: ^6.2.1
    flutter_svg: ^2.0.10+1

    # Audio
    just_audio: ^0.9.42

    # Navigation
    go_router: ^14.2.0
    audio_service: ^0.18.18

    # Network
    dio: ^5.7.0
    flutter_secure_storage: ^9.2.2
    image_picker: ^1.2.1

    # Push Notifications
    firebase_messaging: 15.0.0
    firebase_core: 3.10.0

    # Local Notifications
    flutter_local_notifications: ^17.2.3
    timezone: ^0.9.4

    # Local storage
    shared_preferences: ^2.3.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

    build_runner: ^2.4.13
    freezed: ^2.5.7
    json_serializable: ^6.8.0

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/
        - assets/blobs/sdf/

    shaders:
        - lib/features/player/presentation/player/shaders/fluid_blur.frag
        - lib/features/player/presentation/player/shaders/blob.frag

    fonts:
        - family: Montserrat # Используем для основного текста
          fonts:
              - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
                weight: 100
              - asset: assets/fonts/montserrat/Montserrat-Light.ttf
                weight: 300
              - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
                weight: 400
              - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
                weight: 500
              - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
                weight: 700

        - family: Noah # Используем для акцентных заголовков
          fonts:
              - asset: assets/fonts/noah/Noh95_Am.ttf
                weight: 500
